const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const products = JSON.parse(fs.readFileSync(path.join(root, 'content/products.json'), 'utf8')).products;
const specifics = {
  'purple-brinjal': 'Small round uniformly deep purple eggplants with green calyx. Solid purple skins, absolutely NO white stripes or mottling.',
  'striped-brinjal': 'Small round purple eggplants with clear white stripes and green calyx.',
  'green-brinjal': 'Round pale green eggplants, not purple.',
  'white-brinjal': 'Small ivory white eggplants with green calyx.',
  'long-brinjal': 'Long slender deep purple eggplants.',
  'hybrid-tomato': 'Smooth round red hybrid tomatoes, no lobed heirloom shape.',
  'bellary-onion': 'Large dry red onions with papery reddish-purple skins, no shallots.',
  'small-onion': 'Small red Indian shallots with dry papery skins.',
  'kovai-small-onion': 'Peeled small Indian shallots with clean pale pink flesh, no dry skin.',
  'ash-gourd': 'Pale chalky green waxy winter melon, one whole and a wedge showing white flesh.',
  'snake-gourd': 'Trichosanthes cucumerina snake gourds: three extremely long smooth cylindrical pale green pods, about 50-70 cm long and 3 cm wide, faint white longitudinal stripes, gently curved. No corrugated ridges, no short pods, no ridge gourds.',
  'bitter-gourd': 'Elongated green bitter gourds with distinctive bumpy ridged skin.',
  'small-bitter-gourd': 'Very small green bitter gourds, short oval and bumpy.',
  'drumstick': 'Moringa oleifera edible drumstick seed pods: four very long thin green pods about 45-60 cm long and 1 cm wide, triangular longitudinal ridges, tapered ends, no broad calyx cap. Length-to-width ratio at least 35:1, diagonally arranged. No okra or short fat pods.',
  'cluster-beans': 'Short narrow flat green guar pods in a loose pile.',
  'broad-beans': 'Fresh flat green Indian hyacinth bean pods (avarai).',
  'double-beans': 'Fresh shelled large creamy white and pale pink lima beans, not dried beans.',
  'long-beans': 'Very long thin green cowpea pods, loosely curved.',
  'sundakkai': 'Tiny pea-sized green turkey berries on short branched stems (Solanum torvum).',
  'banana-stem': 'A cylindrical peeled pale ivory banana pseudostem segment with circular cut ends.',
  'banana-flower': 'A whole teardrop-shaped maroon purple banana blossom.',
  'raw-banana': 'Unripe green cooking bananas, no ripe yellow bananas.',
  'elephant-yam': 'Large rough brown elephant foot yam with a wedge showing cream flesh.',
  'colocasia': 'Small brown hairy taro corms, one halved showing white flesh.',
  'purple-yam': 'Dioscorea alata yam, rough brown skin, one cut side showing purple flesh.',
  'karunai-kizhangu': 'Small oblong brown yam tubers (pidi karunai), no large elephant foot yam.',
  'arai-keerai': 'A loose fresh bunch of green amaranth leaves, small ovate leaves on branching tender green stems (Amaranthus).',
  'mulai-keerai': 'Tender young green amaranth bunch with broad ovate leaves and soft pale green stems.',
  'siru-keerai': 'Slender green amaranth stems with small oval leaves, fine tender bunch.',
  'thandu-keerai': 'Mature green amaranth leaves on thick edible pale green stems.',
  'red-amaranth': 'Amaranthus tricolor bunch with broad burgundy red leaves and red stems.',
  'agathi-keerai': 'Sesbania grandiflora sprigs with many small oblong leaflets arranged in pairs along a pinnate stem.',
  'murungai-keerai': 'Moringa oleifera leaves with tiny oval leaflets on delicate multiply branching stems.',
  'manathakkali-keerai': 'Solanum nigrum leafy sprigs with ovate slightly toothed green leaves and a few tiny black berries.',
  'ponnanganni-keerai': 'Alternanthera sessilis sprigs, small opposite elongated oval green leaves.',
  'pasalai-keerai': 'Basella alba Malabar spinach, glossy thick heart-shaped green leaves on fleshy vine stems.',
  'vendhaya-keerai': 'Fresh fenugreek bunch, small trifoliate leaves (three oval leaflets per leaf).',
  'pulicha-keerai': 'Hibiscus sabdariffa gongura sorrel leaves, serrated three-lobed green leaves on reddish stems.',
  'paruppu-keerai': 'Portulaca oleracea purslane, small thick succulent oval leaves on fleshy reddish stems.',
  'mint-leaves': 'Fresh mint bunch, opposite serrated oval textured green leaves.',
  'curry-leaves': 'Murraya koenigii leafy sprigs, glossy narrow oval pointed leaflets arranged along pinnate stems.',
  'dill-leaves': 'Very fine feathery dill foliage in a loose bunch.',
  'coriander-leaves': 'Fresh coriander bunch with delicate lobed bright green leaves and fine stems.',
  'palak-spinach': 'Fresh true spinach bunch with broad smooth dark green oval leaves.',
  'banana-leaf': 'One clean broad green banana leaf with central rib, folded neatly to fit frame.',
  'betel-leaf': 'A small stack of glossy heart-shaped green betel leaves with sharply pointed tips.',
  'bajji-chilli': 'Large long mild pale green frying chillies, not small hot chillies.',
  'fresh-turmeric': 'Fresh orange turmeric rhizomes, one cut end showing deep orange interior, no powder.',
  'button-mushroom': 'Fresh white button mushrooms, whole and one cut showing gills.',
  'oyster-mushroom': 'Fresh oyster mushrooms in pale cream fan-shaped overlapping clusters.',
  'coconut': 'Mature brown hairy coconut, one whole and one half showing white flesh.',
  'tender-coconut': 'Whole fresh green tender coconut, no straw or packaging.',
  'poovan-banana': 'Small slender ripe yellow Poovan bananas in a hand, pointed tips.',
  'robusta-banana': 'A hand of large curved yellow Cavendish bananas.',
  'rasthali-banana': 'Medium ripe yellow Rasthali bananas with light natural russet speckles.',
  'karpooravalli-banana': 'Short plump ripe yellow Karpooravalli bananas with slight brown speckles.',
  'nendran-banana': 'Large long angular ripe golden yellow Nendran plantains with thick skins.',
  'red-banana': 'A hand of plump red bananas with reddish-maroon skins, no yellow skins.',
  'hill-banana': 'Small slender ripe yellow hill bananas, natural lightly speckled skins.',
  'matti-banana': 'Very small short ripe yellow Matti bananas in a hand.',
  'banganapalli-mango': 'Large elongated yellow Banganapalli mangoes without a pronounced hooked beak.',
  'imam-pasand-mango': 'Large oblong ripe Imam Pasand mangoes with greenish-yellow skins.',
  'senthoora-mango': 'Small oval ripe Senthoora mangoes with reddish blush over yellow-green skins.',
  'neelam-mango': 'Small oval ripe golden yellow Neelam mangoes with pointed tips.',
  'totapuri-mango': 'Elongated yellow-green Totapuri mangoes with distinctive hooked parrot-beak tips.',
  'guava': 'Green guavas, one half exposing white flesh and small seeds.',
  'pink-guava': 'Green guavas, one half exposing pink flesh and small seeds.',
  'custard-apple': 'Green sugar apples with rounded segmented knobbly skin, one half showing creamy flesh and black seeds.',
  'jamun': 'Small glossy elongated dark purple jamun fruits, no grapes.',
  'amla': 'Pale green round Indian gooseberries with distinct vertical grooves.',
  'ice-apple': 'Three peeled translucent ivory jelly-like palmyra fruit kernels, not apples or lychees.',
  'fig': 'Fresh ripe purple-green figs, one cut showing pink-red seeded interior.',
  'jackfruit': 'A whole oval green spiky jackfruit, small enough composition to fit fully in frame.',
};
const items = products.map(p => ({
  id: p.id,
  destination: p.image || `/images/uploads/products/${p.id}.jpg`,
  prompt: `Use case: product-mockup. Asset: square mobile catalog photograph. Subject: ${p.name_en} (${p.name_ta}). ${specifics[p.id] || `Show an accurate small representative group of ${p.name_en}, natural size and recognizable shape.`} Input image 1 is the shop logo reference; input image 2 is a setting, composition and lighting reference ONLY. Replace ALL photographed foreground tomatoes with ONLY the specified product. Photorealistic produce with natural skin or leaf texture, soft daylight, realistic shadows on pale cream tabletop; subject entirely within frame in lower two thirds with generous crop-safe margins. Reproduce the green leaf/orange tomato and sun shop mark with exact text "AM Vegetables" on the pale cream background wall in upper third, consistent with reference. No checkerboard, no other text, no prices, no unrelated produce, no packaging. The tomato in the background logo must stay; do not add foreground tomatoes.`,
}));
if (require.main === module) {
  fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(root, 'docs/product-image-prompts.json'), JSON.stringify({
    generator: 'Built-in image_gen tool',
    references: ['app/assets/logo_full.png', 'images/uploads/products/country-tomato.png'],
    products: items,
  }, null, 2) + '\n');
  console.log(`Saved ${items.length} product prompts.`);
}
module.exports = items;
